# name: CI - .NET Framework Tour Management

# on:
#   push:
#     branches: [main]
#     paths-ignore:
#       - 'github/workflows/ci-cd.yml'
#   pull_request:
#     branches: [main]

# jobs:
#   build-and-test:
#     runs-on: windows-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup NuGet
#         uses: NuGet/setup-nuget@v1

#       - name: Restore NuGet packages
#         run: nuget restore **/*.sln

#       - name: Build solution
#         run: msbuild **/*.sln /p:Configuration=Release

#       - name: Run Unit Tests
#         if: always()
#         run: |
#           # Replace with your test runner if MSTest/NUnit/xUnit
#           find . -name "*Tests.dll" | foreach -f {
#             vstest.console.exe $_
#           }


name: CI - Trivy Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Run Trivy scan on current directory
        run: trivy fs --exit-code 1 --severity CRITICAL,HIGH .


