name: CI - .NET Framework Tour Management

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore **/*.sln

      - name: Build solution
        run: msbuild **/*.sln /p:Configuration=Release

      - name: Run Unit Tests
        if: always()
        run: |
          # Replace with your test runner if MSTest/NUnit/xUnit
          find . -name "*Tests.dll" | foreach -f {
            vstest.console.exe $_
          }
