name: CI - Tour Management (.NET Framework)

on:
  push:
    branches: [main]
    paths-ignore:
      -'.github/workflows/ci.yml'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore DotNetFrameworkProject_CE040_CE087/Tour_Management.sln

      # - name: Build Solution
      #   run: msbuild DotNetFrameworkProject_CE040_CE087/Tour_Management.sln /p:Configuration=Release /p:Platform="Any CPU"


      # - name: Build Solution
      #   run: >
      #     "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe"
      #     DotNetFrameworkProject_CE040_CE087/Tour_Management.sln
      #     /p:Configuration=Release /p:Platform="Any CPU"


      # - name: Build Solution
      #   run: |
      #     cmd.exe /c ""C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" DotNetFrameworkProject_CE040_CE087\Tour_Management.sln /p:Configuration=Release /p:Platform="Any CPU""

      - name: Build Solution
        run: |
         cmd.exe /c "\"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe\" DotNetFrameworkProject_CE040_CE087\Tour_Management.sln /p:Configuration=Release /p:Platform=\"Any CPU\""

