name: CI - Tour Management (.NET Framework)

on:
  push:
    branches: [main]
    paths-ignore:
      -'.github/workflows/ci.yml'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore DotNetFrameworkProject_CE040_CE087/Tour_Management.sln

      # - name: Build Solution
      #   run: msbuild DotNetFrameworkProject_CE040_CE087/Tour_Management.sln /p:Configuration=Release /p:Platform="Any CPU"


      # - name: Build Solution
      #   run: >
      #     "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe"
      #     DotNetFrameworkProject_CE040_CE087/Tour_Management.sln
      #     /p:Configuration=Release /p:Platform="Any CPU"


      # - name: Build Solution
      #   run: |
      #     cmd.exe /c ""C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" DotNetFrameworkProject_CE040_CE087\Tour_Management.sln /p:Configuration=Release /p:Platform="Any CPU""

      # - name: Build Solution
      #   run: |
      #    cmd.exe /c "\"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe\" DotNetFrameworkProject_CE040_CE087\Tour_Management.sln /p:Configuration=Release /p:Platform=\"Any CPU\""

      - name: Build Solution with MSBuild
        shell: cmd
        run: |
           "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" DotNetFrameworkProject_CE040_CE087\Tour_Management.sln /p:Configuration=Release /p:Platform="Any CPU"
     
      - name: Run Trivy FS Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: DotNetFrameworkProject_CE040_CE087

  docker-build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build Docker Image
        run: |
          docker build -t tour-management-app -f Dockerfile .
      
      - name: Push Docker Image (optional)
        run: |
          docker tag tour-management-app renshoby/tour-management-app:latest
          docker push renshoby/tour-management-app:latest
