name: CI - Tour Management (.NET Framework)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore packages/Tour_Management.sln

      - name: Build Solution
        run: msbuild packages/Tour_Management.sln /p:Configuration=Release /p:Platform="Any CPU"
